### ISSUE TITLE
whois query bug for IDN tld

### ISSUE THREAD

**Issue by erichuang2015** [ElliotVilhelm/python-domain-validation#1]
hello

I just use this script to query the whois data of  IDN tld   .中国， it is really strange. 

the whois server item for .中国 is "中国": "cwhois.cnnic.cn" , which I added into the constants.py. 

and I set Non-ASCII character support for the IDN by adding the declarations # -*- coding: utf-8 -*- in the  py files.

when I query this domain aa.中国 ， it will throw an exception in the whois client query_whois(domain),and said SERVER_NOT_FOUND

but when I query some others .中国 domains, such as aaa.中国， everything works fine, and return the data successfully.

that is really strange situation here

**Comment by erichuang2015** [comment]
sorry ,  the whois server item I added is punycode format "xn--fiqs8s": "cwhois.cnnic.cn"

**Comment by ElliotVilhelm** [comment]
Looking into this, will update you shortly

**Comment by ElliotVilhelm** [comment]
Firstly, thanks for opening this issue you revealed a bug! The WHOIS_PORTION_SIZE was not a power of 2 which was causing errors when decoding the server response. This has now been resolved.


```
def test_WHOIS_cn():
    sleep(.1)
    whois = WHOIS("aa.中国")
    assert str(whois.creation_date()) == '2013-12-29'
    assert whois.registrar() == '张洪泉'
```

You can test this by running `pytest` in the root directory.

Keep in mind there was an update to this repository where it will now include `creation_date` and `registrar` so the syntax has changed. You can see the difference in the above test. I will update the `README.md` shortly. Thanks so much!

**Comment by erichuang2015** [comment]
hello 

I try again for IDN domains, for example I am querying 我爱你.中国，it will show errors
'utf-8' codec can't decode byte 0xe9 in position 63: unexpected end of data
Registrar_not_found

my python version is Python 3.6.0， the repository  code used is the latest one here，my codes is as below

from domain_validation.whois import WHOIS
whois = WHOIS("我爱你.中国")
print(whois.registrar())
