### ISSUE TITLE
IDN  domains  encoding error

### ISSUE THREAD

**Issue by erichuang2015** [ElliotVilhelm/python-domain-validation#4]
I try again for IDN domains, for example I am querying 我爱你.中国，it will show errors
'utf-8' codec can't decode byte 0xe9 in position 63: unexpected end of data
Registrar_not_found

my python version is Python 3.6.0， the repository  code used is the latest one here，my codes is as below

from domain_validation.whois import WHOIS
whois = WHOIS("我爱你.中国")
print(whois.registrar())

_Originally posted by @erichuang2015 in https://github.com/ElliotVilhelm/python-domain-validation/issues/1#issuecomment-428090436_

**Comment by erichuang2015** [comment]
and also from your test codes below

whois = WHOIS("yo.cn")
assert str(whois.creation_date()) == '2003-03-17'
assert whois.registrar() == '浙江贰贰网络有限公司'


errors thrown

Traceback (most recent call last):
  File "whois.py", line 3, in <module>
    assert str(whois.creation_date()) == '2003-03-17'
AssertionError

**Comment by ElliotVilhelm** [comment]
Looking into this, thanks for the feedback

**Comment by ElliotVilhelm** [comment]
```python
def test_WHOIS_utf_encoding():
    sleep(.1)
    whois = WHOIS("我爱你.中国")
    assert str(whois.creation_date()) == '2004-01-06'
    assert whois.registrar() == 'Registrar_not_found'
```

Looks like this server uses utf-16 encoding, I have  written a fall back to utf-16. This has been tested and is working now.

**Comment by ElliotVilhelm** [comment]
Not sure why the README was failing for you, it is part of the travis test and is certainly passing. You may have just been shut out by the server on that request? Can you try again and reproduce? It is working fine on my end.
