### ISSUE TITLE
Transition package to production server from test.pypi.org 

### ISSUE THREAD

**Issue by gillespiecd** [ElliotVilhelm/python-domain-validation#5]
There have been errors with the test server 503ing when installing`domain_validation` with `requirements.txt`. It would be more sturdy to use the prod instance of pypi.

Error:
`HTTPSConnectionPool(host='test.pypi.org', port=443): Max retries exceeded with url:`

**Comment by ElliotVilhelm** [comment]
Looking into this

**Comment by ElliotVilhelm** [comment]
`pip3 install domain_validation`
